Develop
olegVolkov03991/java-explore-with-me pull request #1
Opened 2022-12-30 18:32 UTC by olegVolkov03991

2023-01-05 13:28 UTC, olegVolkov03991 commented
я понятия не имею почему гит не видит файлы в папке target, в группе ребята так же не смогли помочь, ничего не помогает.
локально все собирается и работает.
у меня больше нет идей...

2023-01-07 07:00 UTC, EugeneLenkevich requested changes
Привет, Олег, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

Далее, 
наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему будут оценивать навыки. Я оставил кучку коментариев, будут вопросы, задавай, не стесняйся, немножко допилить осталось :)

Удачи!

PS

и посмотри, пожалуйста, почему ПР автотесты не проходит :)

![image](https://user-images.githubusercontent.com/109306643/211135575-43c237bd-4385-46ca-a5d5-3cf33a61fa5e.png)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/model/Category.java
> +@Data
С этой аннотацией нало поаккурантей. Она генерирует equals и hashCode на основании всех полей. 
Однако, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
Плюс еще некоторые поля могут быть ленивыми коллекциями и в момент обращения бдут генерироваться sql-запросы, которые и не нужны в данный момент

Т.е. надо или переопределить руками или указать через аннотации как генерировать эти методы :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/model/dto/CategoryInputDto.java
> +@Data
Для dto она в принципе норм :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/model/dto/CategoryMapper.java
> +public class CategoryMapper {
Объект, который производит маппинг можно, так же, сделать отдельным бином. Это позволит оформить все в единой(спринговой) парадигме и лишний раз избежать использования статических методов, которые являются жесткими ссылками.

Однако, это вопрос дискуссионный.
С другой стороны, в этом случае, мы пихаем в спринговый контекст дополнительный бин :)

Что думаешь на этот счет? :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/repository/CategoryRepository.java
> +    Page<Category> getCategoriesByIdInOrderByIdAsc(List<Long> id,
В метод передается объект pageable, в названии метода тоже есть указание метода сортировки, тут может быть некоторый конфликт, OrderByIdAsc - это лучше убрать, а сортировку оставить через pageable

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/services/CategoryServiceImpl.java
> +        if (id == 0) {
Какой то костыль, какая то магия, соверщенно неочевидно зачем так делать :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/services/CategoryServiceImpl.java
> +    public List<CategoryOutputDto> getAllById(List<Long> id,
id - единственное число
ids - можественное, пусть так параметр называется, так гораздо наглядней :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/services/CategoryServiceImpl.java
> +                log.warn("error");
А что тут за ошибка, добавить бы еще описания :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/services/CategoryServiceImpl.java
> +            categories.stream().forEach(category -> id.remove(category.getId()));
Вообще, изменять входщие параметры не очень правильно, этого никто не ожидает, этот объект же потом кто-то может еще где то использовать и будет ожидать что объект остался неизменным. Если уж так надо то можно сделать копию объекта и ее уже изменять, хотя я не совсем понимаю смысл этих манипуляций, это какая то проверка, а нужна ли она вообще? :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/services/CategoryServiceImpl.java
> +        if (id == 0) {
Опять неочевидная история, потом такой адский гимор будет такое отлаживать :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/compilations/model/dto/CompilationInputDto.java
> +    Set<Long> events;
private

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/compilations/model/dto/CompilationOutputDto.java
> +    Set<Event> events;
private

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/compilations/repository/CompilationRepository.java
> +    @Transactional
То что ты вспомнил про эту аннотацию - это здорово, только лучще ее вешать на методы сервисов, методы репозитория и так транзакционны (свойство СУБД), эта же аннотация обычно нужна для того, чтобы оформлять логические транзакции, то есть когда у нас есть несколько изменяющих запросов, они должны примениться или откатиться одновременно в случае ошибки :)

https://habr.com/ru/post/682362/

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/services/CategoryServiceImpl.java
> +        if(categoryRepository.findByName(categoryInputDto.getName()) != null){
categoryRepository.existsByName(name)

А попробуй создать вот такой метод, exists-запрос более легкий чем select, более оптимально :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/events/model/Event.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Давай попробуем настроить фоматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates


И зачем кстати сериализация в JSON для полей сущности, данные же перекладываются в dto и уже dto сериализуются в контроллерах :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/events/services/EventServiceImpl.java
> +                    .filter(e -> e.getParticipantLimit() > requestRepository.getCountConfirmedRequestByEventId(e.getId()))
Для каждого элемента коллекции будет вызван отдельный sql-запрос, это не очень оптимально :)
А не получится ли фильтрацию данных произвести на уровне СУДБ, там это происходит наиболее оптимально, то есть как то докрутить sql-запрос

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/events/services/EventServiceImpl.java
> +    public EventOutputDto rejectEventByInitiator(Long userId, Long eventId) {
Тут бы тоже @Transactional
Да и вообще на всех методах сервисов где происходит изменение информации, на многих есть, но местами упущено :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/user/repository/UserRepository.java
> +    Page<User> getUsersByIdIsInOrderByIdAsc(List<Long> id, Pageable pageable);
Опять таки OrderByIdAsc и Pageable :)

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/user/services/UserServiceImpl.java
> +        if (userRepository.findByName(userInputDto.getName()) != null) {
existsByName

2023-01-07 07:00 UTC, EugeneLenkevich commented on ewm-service/src/main/resources/schema.sql
> +    description VARCHAR(255),
VARCHAR(255),

255 символов для описания маловато наверно, можно сделать тип text например :)

2023-01-09 21:46 UTC, olegVolkov03991 commented on ewm-service/src/main/java/ru/practicum/ewm/categories/model/dto/CategoryMapper.java
> +public class CategoryMapper {
я честно говоря так не могу понять, что такое на самом деле "бин". Вроде понятно, 
но одновременно не понимаю.

2023-01-09 23:22 UTC, olegVolkov03991 commented on ewm-service/src/main/java/ru/practicum/ewm/events/services/EventServiceImpl.java
> +                    .filter(e -> e.getParticipantLimit() > requestRepository.getCountConfirmedRequestByEventId(e.getId()))
я попробовал как-то изменить запрос, но у меня что-то не особо выходит, можешь подсказать как можно улучшить ?

2023-01-09 23:57 UTC, olegVolkov03991 commented
не проходит один тест на удаления пользователя, не могу понять каким образом он возвращает какой-то результат. По замечаниям сделал то что понял, пару замечаний оставил, потому что не получилось переделать или не понял как переделать)

2023-01-10 04:30 UTC, EugeneLenkevich commented
> я понятия не имею почему гит не видит файлы в папке target, в группе ребята так же не смогли помочь, ничего не помогает. локально все собирается и работает. у меня больше нет идей...

target в игноре, он там и должен быть :)

![image](https://user-images.githubusercontent.com/109306643/211462265-9cbed063-10d8-47e8-9f77-e1829774f0cb.png)

2023-01-10 04:39 UTC, EugeneLenkevich commented
> не проходит один тест на удаления пользователя, не могу понять каким образом он возвращает какой-то результат. По замечаниям сделал то что понял, пару замечаний оставил, потому что не получилось переделать или не понял как переделать)


На счет тестов лучше сразу спрашивать наставника, наставник гораздо больше в теме этих тестов :)

2023-01-10 05:39 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/categories/model/dto/CategoryMapper.java
> +public class CategoryMapper {
Точно так же как и сервис. повесить аннотациюю и инжектить, вот примерчик

![image](https://user-images.githubusercontent.com/109306643/211470345-cc9bae4c-9cc0-48d7-9bd1-599b5a7af5e5.png)

![image](https://user-images.githubusercontent.com/109306643/211470432-5f0326d1-ca77-48cb-bd62-9dddb0131b7e.png)

2023-01-10 05:51 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/events/services/EventServiceImpl.java
> +                    .filter(e -> e.getParticipantLimit() > requestRepository.getCountConfirmedRequestByEventId(e.getId()))
Посмотрел, сложноватый запрос получается, без тестов и без БД под рукой я не напишу )
Смысл тут в  том чтобы вот судя подставить или подзапрос который вернет id таких событий 

![image](https://user-images.githubusercontent.com/109306643/211471865-13cfb1bd-5ad5-4b8d-8bfa-1894276876b4.png)

... или руками подставить идшники (котороый можно полдучить отдельно, например, запросом ниже)

Или можно хотя бы количество вытащить за один запрос

![image](https://user-images.githubusercontent.com/109306643/211471553-1f811cef-b449-4be6-ac77-a9b307190969.png)

2023-01-10 06:03 UTC, EugeneLenkevich requested changes
Привет, спасибо за доработку, на коменты вроде все ответил

Мне кажется ты не тот архив приложил к таску,  там ссылка на другой репозиторий, по истории нашел нужный :)

А так же, посмотри вот что, оказывается проект не совсем верно настроен, он в итоге ничего и не собирает :) 

В главный pom.xml добавь два модуля

![image](https://user-images.githubusercontent.com/109306643/211473008-3920cf5c-5fbe-43fa-ad59-536997392b5e.png)

```
	<modules>
		<module>ewm-service</module>
		<module>stats-server</module>
	</modules>
```

Далее в pom.xml модулей тебе надо добавить compiler-plugin

![image](https://user-images.githubusercontent.com/109306643/211473246-86e8f930-aa1e-4da6-8b84-1036dff5dee2.png)

```
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

Далее обнови настройки мавена и попробуй собрать, mvn clean package

![image](https://user-images.githubusercontent.com/109306643/211474052-0fe2866a-ef3a-45ad-9427-1c5f0c90de25.png)


Начни с правильной настройки проекта, далее, кстати, надо будет добавить все зависимости, Идея в этом поможет, на красном импорте Ctrl+Space->Add dependency

2023-01-10 14:48 UTC, olegVolkov03991 commented
![image](https://user-images.githubusercontent.com/98637747/211582139-e6acf6d1-1810-41e2-9206-4f5fdcd0cc1a.png)


если я правильно понял, то автотесты не пропускают этот файл EwmServiceApplicationTests, но локально с этого файла тесты проходит, я уже вообще не понимаю что тут происходит, ошибки в принципе не понимаю, локально некоторые нормально, тогда почему тут ошибка то

2023-01-10 14:49 UTC, olegVolkov03991 commented
тут уже такой бред, уже давно ничего не могу понять

2023-01-10 16:16 UTC, EugeneLenkevich commented
> если я правильно понял, то автотесты не пропускают этот файл EwmServiceApplicationTests, но локально с этого файла тесты проходит, я уже вообще не понимаю что тут происходит, ошибки в принципе не понимаю, локально некоторые нормально, тогда почему тут ошибка то

Да у тебя из-за него сборка падает. Просто удали его, в этом задании локальные тесты не требуются (а так, к БД подключится не может потому и падает) Как удалишь посмотри пройдут ли автотесты, если нет то иди к наставнику :)

![image](https://user-images.githubusercontent.com/109306643/211604311-ea08865a-528e-4528-8ffd-25f996560af1.png)

2023-01-12 04:30 UTC, EugeneLenkevich approved these changes
Вот это упорство, по комитам прямо таки остросюжетный триллер!  
Я уж начал переживать, но вижу ок все, тесты проходят, ты молодец, такая воля - это дорогого стоит, серьезно =)

2023-01-12 11:55 UTC, merged